In [1]:
import torch
torch.__version__

'1.3.1'

In [4]:
x=torch.rand(5,3)
y=torch.rand(5,3)

In [8]:
x

tensor([[0.5051, 0.7017, 0.0170],
        [0.1441, 0.2476, 0.5710],
        [0.0452, 0.8690, 0.2387],
        [0.5709, 0.0098, 0.6993],
        [0.3203, 0.5124, 0.1010]])

In [6]:
y

tensor([[0.6415, 0.5819, 0.3311],
        [0.0086, 0.4336, 0.5773],
        [0.3360, 0.5421, 0.1845],
        [0.4490, 0.1557, 0.5100],
        [0.0162, 0.5474, 0.3124]])

In [9]:
x.size()

torch.Size([5, 3])

In [10]:
add=x + y

In [12]:
print(add)

tensor([[1.1466, 1.2836, 0.3481],
        [0.1527, 0.6813, 1.1483],
        [0.3812, 1.4111, 0.4232],
        [1.0199, 0.1655, 1.2094],
        [0.3364, 1.0598, 0.4134]])


In [13]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [14]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

### liner

In [49]:
x = torch.tensor([[1.,2.,3.],[4.,5.,6.]],requires_grad=True)

In [45]:
y = x+1
z = 2*y*y
J = torch.mean(z)

In [46]:
J.backward()

In [47]:
x.requires_grad, y.requires_grad, z.requires_grad

(True, True, True)

In [48]:
x.grad

tensor([[1.3333, 2.0000, 2.6667],
        [3.3333, 4.0000, 4.6667]])

In [50]:
y = x+1
z =torch.sum(2*y*y) 

In [51]:
z

tensor(278., grad_fn=<SumBackward0>)

In [52]:
z.backward()

In [53]:
x.grad

tensor([[ 8., 12., 16.],
        [20., 24., 28.]])

In [54]:
x = torch.randn(3,4,requires_grad=True)

In [55]:
b = torch.randn(3,4,requires_grad=True)

In [56]:
x

tensor([[ 2.4921,  0.3292,  0.2324, -0.8859],
        [-1.3799,  1.6637, -0.5004, -0.4578],
        [-0.2573, -2.0164,  0.3258,  0.0283]], requires_grad=True)

In [57]:
b

tensor([[-0.2642,  0.3113,  0.0120, -1.3174],
        [ 0.1307,  1.8577,  0.0130,  0.3950],
        [-0.3580,  1.3666,  0.2026, -0.4438]], requires_grad=True)

In [58]:
t = 2*x*x + b
y = t.sum()
y

tensor(34.9634, grad_fn=<SumBackward0>)

In [59]:
y.backward()

In [60]:
x.grad

tensor([[ 9.9684,  1.3170,  0.9295, -3.5436],
        [-5.5196,  6.6548, -2.0017, -1.8311],
        [-1.0293, -8.0657,  1.3033,  0.1134]])

In [61]:
4*x

tensor([[ 9.9684,  1.3170,  0.9295, -3.5436],
        [-5.5196,  6.6548, -2.0017, -1.8311],
        [-1.0293, -8.0657,  1.3033,  0.1134]], grad_fn=<MulBackward0>)

In [63]:
import numpy as np

In [65]:
x_values = [i for i in range(11)]
x_train = np.array(x_values, dtype=np.float32)
x_train = x_train.reshape(-1, 1)
x_train
x_train.shape

(11, 1)

In [66]:
x_train

array([[ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]], dtype=float32)

In [67]:
y_values = [2*i + 1 for i in x_values]
y_train = np.array(y_values, dtype=np.float32)
y_train = y_train.reshape(-1, 1)
y_train.shape

(11, 1)

In [68]:
import torch
import torch.nn as nn

In [69]:
class LinearRegressionModel(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearRegressionModel, self).__init__()
        self.linear = nn.Linear(input_dim, output_dim)  

    def forward(self, x):
        out = self.linear(x)
        return out

In [70]:
input_dim = 1
output_dim = 1

model = LinearRegressionModel(input_dim, output_dim)

In [71]:
model

LinearRegressionModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)

In [72]:
epochs = 1000
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
criterion = nn.MSELoss()

In [73]:
for epoch in range(epochs):
    epoch += 1
    # 注意转行成tensor
    inputs = torch.from_numpy(x_train)
    labels = torch.from_numpy(y_train)

    # 梯度要清零每一次迭代
    optimizer.zero_grad() 

    # 前向传播
    outputs = model(inputs)

    # 计算损失
    loss = criterion(outputs, labels)

    # 返向传播
    loss.backward()

    # 更新权重参数
    optimizer.step()
    if epoch % 50 == 0:
        print('epoch {}, loss {}'.format(epoch, loss.item()))

epoch 50, loss 0.014054547995328903
epoch 100, loss 0.008016204461455345
epoch 150, loss 0.0045721265487372875
epoch 200, loss 0.002607773058116436
epoch 250, loss 0.001487374771386385
epoch 300, loss 0.000848358147777617
epoch 350, loss 0.0004838676250074059
epoch 400, loss 0.0002759790513664484
epoch 450, loss 0.00015740757226012647
epoch 500, loss 8.977791003417224e-05
epoch 550, loss 5.121099457028322e-05
epoch 600, loss 2.9206259569036774e-05
epoch 650, loss 1.6657537344144657e-05
epoch 700, loss 9.500843589194119e-06
epoch 750, loss 5.419644367066212e-06
epoch 800, loss 3.091541202593362e-06
epoch 850, loss 1.763068667059997e-06
epoch 900, loss 1.0057904091809178e-06
epoch 950, loss 5.732178465223114e-07
epoch 1000, loss 3.269897206337191e-07


In [74]:
predicted = model(torch.from_numpy(x_train).requires_grad_()).data.numpy()
predicted

array([[ 0.99893636],
       [ 2.9990895 ],
       [ 4.9992423 ],
       [ 6.9993954 ],
       [ 8.999549  ],
       [10.9997015 ],
       [12.999855  ],
       [15.000009  ],
       [17.00016   ],
       [19.000313  ],
       [21.000465  ]], dtype=float32)

In [75]:
torch.save(model.state_dict(), 'model.pkl')
model.load_state_dict(torch.load('model.pkl'))

<All keys matched successfully>